version: '3'

services:

    db:
        image: mysql:5.6
        ports:
            -   3306:3306

        environment: 
            MYSQL_ROOT_PASSWORD:    password
            MYSQL_DATABASE:         cakephp
            MYSQL_USER:             cakephp
            MYSQL_PASSWORD:         cakephp

        command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        volumes: 
            -   /var/lib/mysql
            -   /var/log/mysql

    adminer:
        image: adminer
        ports:
            -   9101:8080
